### ISSUE TITLE
Problems with package for wsl-translinux

### ISSUE THREAD

**Issue by cerebrate** [patrick330602/wslu#2]
Just a couple of issues to resolve before I can accept it into the repository:

1. Looks like the scripts are being placed in /usr/bin with owner and group as the wsl user (i.e., showing on my system as avatar/avatar); since they're in /usr/bin, they need to install as root/root.

2. The package is taking a dependency on ppa-purge . While that works on Ubuntu, ppa-purge isn't an installable package on Debian, which breaks the install:
```
$ sudo apt show ppa-purge
Package: ppa-purge
State: not a real package (virtual)
N: Can't select candidate version from package ppa-purge as it has no candidate
N: Can't select versions from package 'ppa-purge' as it is purely virtual
N: No packages found
```

...or, if manually installed, subsequent updates:

```
$ sudo apt upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 wslu : Depends: ppa-purge but it is not installable
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
[1]    24214 exit 100   sudo apt upgrade
```

Once these are resolved, I'll be happy to accept it.

**Comment by patrick330602** [comment]
Noted, after fixing, I will create another pr

**Comment by patrick330602** [comment]
It should be fixed now... I will keep this is Sue open until there is no problem

**Comment by cerebrate** [comment]
Problems are indeed all fixed, and I've added it to the repo.
